apiVersion: v2
name: omni-resource-app
description: A Helm chart featuring a wide variety of Kubernetes resource kinds to test graph visualization diversity.
type: application
version: 0.1.0
appVersion: "3.0.0"
